name: Deploy step function to AWS 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - feature/*

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_URL: ${{ steps.export-image-url.outputs.IMAGE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }} .

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Export IMAGE_URL
        id: export-image-url
        run: |
          echo "IMAGE_URL=${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}" >> $GITHUB_OUTPUT

  deploy-step-function:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Serverless Framework
        run: |
          npm install -g serverless

      - name: Install project dependencies
        run: |
          npm ci

      - name: Debug image URL
        run: echo "IMAGE_URL = ${{ needs.build-and-push-image.outputs.IMAGE_URL }}"

      - name: Deploy step function
        uses: serverless/github-action@v3.2
        with:
          args: deploy --verbose
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          DYNAMO_TABLE_NAME: ${{ secrets.DYNAMO_TABLE_NAME }}
          IMAGE_URL: ${{ needs.build-and-push-image.outputs.IMAGE_URL }}
